---
title: "macro_issues"
author: "Ricardo Mayer"
date: "October 19, 2017"
output:
  html_document: default
  word_document: default
---

1. Consumption-led expansion 

  - Overview: Consumption lead expansions may build up fragilities through excessive lending. This either hamper growth in the medium run or set the stage for a financial crisis. It is an extended phenomenon: the BIS, bacause of data availability, focus on advanced economies but it is also ubiquitous  in sub-saharan and latin american economies
  
      + Obs 1: In advanced economies is a product of zero nominal rates and monetary stimulus to clean up balance sheets. In latin america is the financial market development reaching to middle and midle-low income groups grantig them consumtion loans (but also housing debt, does this matter?)
  
      + Idea 1: How can we sustain this positive impulse? What are appropriate policies? How the different origins of credit expansion (intensive versus extensive margins) 
      
      + Idea 2: If household debt service ratio is the ideal variable but is not available, as in many latin american countries, what are good proxies?
      
  
  - Literature
      + Kharruni and Kohlscheen, 2017, BIS. http://www.bis.org/publ/qtrpdf/r_qt1703e.pdf
      
        Abstract: *GDP growth has increasingly been led by consumption. However, consumption-led expansions tend to be significantly weaker than when growth is driven by other components of aggregate demand, often because of the build-up of imbalances. We show that while factors such as credit growth and rising house prices can boost consumption in the short run, the incidence of consumption-led growth and rising debt service ratios significantly dampen growth in the medium to long run. Policies that address the build-up of imbalances and strengthen investment are therefore central to fostering durable growth* 
      
        Here is Bloomberg's extract:
        The global economy’s recovery from the financial crisis may be overly dependent on domestic consumption and at risk of failing, according to the Bank for International Settlements.

        In its quarterly review, the organization said the number of advanced economies in consumption-led expansions has increased in recent years. In addition to generally being weaker than other forms of growth, this type can also sow the seeds of future slumps. This is particularly the case if they are driven by a buildup of debt, as happened prior to the crisis in 2008.
      
        Increasing shares of private consumption in gross domestic product can be a leading indicator of future growth slowdowns,” BIS economists Enisse Kharroubi and Emanuel Kohlscheen said in the BIS report published on Monday. “High household debt service ratios tend to become a potent drag on economic growth, frequently leading to costly deleveraging processes.

        One of the drivers of consumption in recent years has been monetary stimulus since 2008, with the European Central Bank and others cutting interest rates below zero or implementing massive bond-buying programs. That extraordinary stimulus has also fueled talk that central banks are fueling the next asset-price bubble.

        “The increasing prevalence of consumption-led growth since 2012 therefore presents new challenges for policymakers in several economies,” Kharroubi and Kohlscheen said. “Policies that address the build-up of imbalances and strengthen investment are thus central in fostering sustainable growth.”



2. Macro-prudential policies

   - Overview (hablar con esteban). Estamos en un risk taking period, fueled by low real and nominal rates, do we stop this? how? lean or clean?. A decade after the U.S. housing market collapsed, Federal Reserve officials are watching rising apartment towers as the next potential asset-price bubble, which could add to the debate about the pace of interest-rate hikes this year.
  
   - BIS September 2017 remarks: **Strong outlook with low inflation spurs risk-taking** http://www.bis.org/publ/qtrpdf/r_qt1709a.htm:
      
      The shifting outlook for the future paths of monetary policy and increased US policy uncertainty put strong downward pressure on the US dollar. As macro news was also better than expected globally while disappointing in the United States, the dollar depreciated vis-à-vis all major advanced economy and EME currencies. The dollar lost most ground against the euro, given the strengthening economic outlook in the euro area and monetary policy signals.

      Low measures of volatility and a depreciating dollar supported a "risk-on" phase. It whetted investors' appetite for EME assets as carry trades delivered large returns. Equity market investors used record amounts of margin debt to lever up their investments, even though price/earnings ratios indicated that equity valuations might be stretched by historical standards. And there were some signs of search for yield in debt markets: issuance volumes in leveraged loan and high-yield bond markets rose while covenant standards eased.
      
      *A "risk-on" phase*: As is typical for periods of low volatility and a falling dollar, a "risk-on" phase prevailed. 
      Against the backdrop of persistent interest rate differentials and a depreciating dollar, returns from carry trades rose sharply and EME equity and bond funds saw large inflows during the period under review (Graph 7, first panel). Speculative positions also pointed to patterns of broader carry trade activity: large net short positions in funding currencies, such as the yen and Swiss franc, and large net long positions in EME currencies and the Australian dollar (Graph 4, right-hand panel).

      Equity market investors also employed record amounts of margin debt to lever up their investments. In fact, margin debt outstanding was substantially higher than during the dotcom boom and around 10% higher than its previous peak in 2015 (Graph 7, second panel).
      
      The relative number of companies rated A or better has fallen especially sharply, while the share of worst-rated (C or lower) companies has increased. Taken together, this suggests that, in the event of a slowdown or an upward adjustment in interest rates, high debt service payments and default risk could pose challenges to corporates, and thereby create headwinds for GDP growth.

  - FEDs remark Jan 2017: Fed Chair Janet Yellen cited commercial real estate prices as “high” in a speech at Stanford University on Jan. 19. That message has been echoed by Governor Jerome Powell, who warned “low rates may lead to a reach for yield,” as well as Boston Fed President Eric Rosengren, who cited luxury housing in his city. (https://www.bloomberg.com/news/articles/2017-02-02/yellen-eyes-commercial-real-estate-froth-as-fed-weighs-17-risks)
  
   + Obs 1: Que es el riesgo sistemico, exactamente? como cambian las opciones con las definiciones?
      
    + Obs 2: how do we identify reach for yield
      
   + Idea 1:
      
   + Idea 2:
  
  - Literature: Frankel 2017
  
  
  
3. Macro and inequality interaction

   - Overview
  
   + Obs 1: Should policy makers target inequality or be concerned with a trade off woth growth? One view: when potential gains in growth rates are small (USA, EU) it is worthwile to focus on inequality. But in ALC and other, there is much to be missed by not targetig growth. One caveat is that policy has much larger distributive effect that growth ones, except for really bad policies. And small changes can in general have low efficiency effects while producing large redristributions.  https://piie.com/system/files/documents/furman20171012paper.pdf   and https://piie.com/system/files/documents/rodrik20171013ppt.pdf
   
   + Obs 2: formal models need to feature heterogeneous agents to explore inequality. Challenging in general. Per Krusell notes that AKMWW paper and implementation is a promising step towards a spur of new research (easier to use)
  
   + Idea 1 Going forward, as we continue to rethink macroeconomics, better incorporating welfare
and distributional considerations into models and understanding how they relate to specific
policy instruments. The fact that we cannot agree on the appropriate social welfare function is
not an argument for choosing one particular social welfare function—the average of incomes—
that is inconsistent with the way most policymakers describe their ultimate goals.
   
   + Idea 2

  - Literature: 
      + When Inequality Matters for Macro and Macro Matters for Inequality, by SeHyoun Ahn, Greg Kaplan, Benjamin Moll, Thomas Winberry, Christian Wolf. NBER Working Paper No. 23494. Issued in June 2017. http://www.nber.org/papers/w23494
      Abstract: *We develop an efficient and easy-to-use computational method for solving a wide class of general equilibrium heterogeneous agent models with aggregate shocks, together with an open source suite of codes that implement our algorithms in an easy-to-use toolbox. Our method extends standard linearization techniques and is designed to work in cases when inequality matters for the dynamics of macroeconomic aggregates. We present two applications that analyze a two-asset incomplete markets model parameterized to match the distribution of income, wealth, and marginal propensities to consume. First, we show that our model is consistent with two key features of aggregate consumption dynamics that are difficult to match with representative agent models: (i) the sensitivity of aggregate consumption to predictable changes in aggregate income and (ii) the relative smoothness of aggregate consumption. Second, we extend the model to feature capital-skill complementarity and show how factor-specific productivity shocks shape dynamics of income and consumption inequality.*
        Comments by Per Krusell: http://www.nber.org/chapters/c13929.pdf

    

4. Monetary Policy

  - Overview 
      + Idea 1
      + Idea 2
      



